// HOMESCREEN //
export const PRODUCT_LIST_REQUEST =  'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS =  'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL =  'PRODUCT_LIST_FAIL';

//PRODUCTSCREEN//
export const SELECETED_PRODUCT_REQUEST =  'SELECETED_PRODUCT_REQUEST';
export const SELECETED_PRODUCT_SUCCESS =  'SELECETED_PRODUCT_SUCCESS';
export const SELECETED_PRODUCT_FAIL =  'SELECETED_PRODUCT_FAIL';