export default {
    products: [{
            _id: '1',
            name: 'Shirts Thermal Workout',
            category: 'Shirts',
            image: '/images/product_img_1.jpg',
            price: 1259,
            brand: 'Hiskywin',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '2',
            name: 'Nike Sweatshirt',
            category: 'Shirts',
            image: '/images/product_img_2.jpg',
            price: 870,
            brand: 'Nike',
            rating: 5,
            numReviews: 51,
            countInStock: 3,
        },
        {
            _id: '3',
            name: 'Adidas Mens Long Hoodie',
            category: 'Shirts',
            image: '/images/product_img_3.jpg',
            price: 759,
            brand: 'Adidas',
            rating: 4,
            numReviews: 45,
            countInStock: 4,
        },
        {
            _id: '4',
            name: 'Under Tricot Joggers',
            category: 'Pants',
            image: '/images/product_img_4.jpg',
            price: 990,
            brand: 'Under Armour',
            rating: 2.5,
            numReviews: 198,
            countInStock: 2,
        },
        {
            _id: '5',
            name: 'Fleece Jogger',
            category: 'Pants',
            image: '/images/product_img_5.jpg',
            price: 1119,
            brand: 'Champion',
            rating: 3.5,
            numReviews: 89,
            countInStock: 1,
        },
        {
            _id: '6',
            name: 'Joggers Pants Long Multi-Pockets',
            category: 'Pants',
            image: '/images/product_img_6.jpg',
            price: 985,
            brand: 'Aelfric Eden',
            rating: 4.5,
            numReviews: 45,
            countInStock: 0,
        },
        {
            _id: '7',
            name: 'Aelfric Eden Multi-Pockets',
            category: 'Pants',
            image: '/images/product_img_7.jpg',
            price: 985,
            brand: 'Aelfric Eden',
            rating: 4.5,
            numReviews: 45,
            countInStock: 7,
        },
        {
            _id: '8',
            name: 'Joggers Pants Long Pockets',
            category: 'Pants',
            image: '/images/product_img_8.jpg',
            price: 985,
            brand: 'Aelfric Eden',
            rating: 4.5,
            numReviews: 45,
            countInStock: 5,
        },
        {
            _id: '9',
            name: 'Aelfric Eden Mens Joggers',
            category: 'Pants',
            image: '/images/product_img_9.jpg',
            price: 985,
            brand: 'Aelfric Eden',
            rating: 4.5,
            numReviews: 45,
            countInStock: 0,
        },
        {
            _id: '10',
            name: 'Aelfric Long Multi-Pockets',
            category: 'Pants',
            image: '/images/product_img_10.jpg',
            price: 985,
            brand: 'Aelfric Eden',
            rating: 4.5,
            numReviews: 45,
            countInStock: 4,
        },
        {
            _id: '11',
            name: 'Pants Long Multi-Pockets',
            category: 'Pants',
            image: '/images/product_img_11.jpg',
            price: 985,
            brand: 'Aelfric Eden',
            rating: 4.5,
            numReviews: 45,
            countInStock: 9,
        },
        {
            _id: '12',
            name: 'Aelfric Eden Mens ',
            category: 'Pants',
            image: '/images/product_img_12.jpg',
            price: 219855,
            brand: 'Aelfric Eden',
            rating: 4.5,
            numReviews: 45,
            countInStock: 1,
        },
    ],
};